CREATE DATABASE VETERINARIA;

USE VETERINARIA;

CREATE TABLE USER(
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    IDENTIFICATION VARCHAR(20) UNIQUE,
    PHONE VARCHAR(20) UNIQUE,
    NAME VARCHAR(100),
    LASTNAME VARCHAR(100),
    EMAIL VARCHAR(255) UNIQUE,
    PASS VARCHAR(200),
    CARGO ENUM('ADMIN','PROPIETARIO','TRABADOR'),
    STATE ENUM('ACTIVO','INACTIVO')
);

CREATE TABLE VET(
    ID_VET INT AUTO_INCREMENT PRIMARY KEY,
    IDENTIFICATION_ADMIN INT UNIQUE,
    ADDRESS VARCHAR(255) UNIQUE,
    PROFITS FLOAT(10,2),
    LOSS FLOAT(10,2),
    STATE ENUM('ACTIVO','INACTIVO'),
    FOREIGN KEY (IDENTIFICATION_ADMIN) REFERENCES USER(ID_USER)
);

CREATE TABLE MANAGER(
    ID_MANAGER INT AUTO_INCREMENT PRIMARY KEY,
    ADDRESS_MANAGER VARCHAR(200),
    PHONE_MANAGER VARCHAR(20) UNIQUE,
    FULLNAME VARCHAR(200),
    STATE ENUM('ACTIVO','INACTIVO')
);

CREATE TABLE RACE(
    ID_RACE INT AUTO_INCREMENT PRIMARY KEY,
    RACE VARCHAR(100),
    ID_VET INT,
    STATE ENUM('ACTIVO','INACTIVO'),
    FOREIGN KEY (ID_VET) REFERENCES VET(ID_VET)

); 

CREATE TABLE PET(
    ID_PET INT AUTO_INCREMENT PRIMARY KEY,
    ID_VET INT,
    IDENTIFICATION_PET INT UNIQUE,
    NAME_PET VARCHAR(255),
    ID_MANAGER INT,
    ID_RACE INT,
    COLOR VARCHAR(90),
    SIZE VARCHAR(90),
    AGE VARCHAR(90),
    WEIGHT VARCHAR(90),
    STATE ENUM('ACTIVO','INACTIVO'),
    FOREIGN KEY (ID_VET) REFERENCES VET(ID_VET),
    FOREIGN KEY (ID_MANAGER) REFERENCES MANAGER(ID_MANAGER),
    FOREIGN KEY (ID_RACE) REFERENCES RACE(ID_RACE)
);


CREATE TABLE JOBS(
    ID_JOBS INT AUTO_INCREMENT PRIMARY KEY,
    ID_VET INT,
    ID_USER INT,
    IDENTIFICATION_PET INT, 
    JOB TEXT,    
    COSTS FLOAT(10,2),
    COST_DESCRIPTION TEXT,
    STATE ENUM('ACTIVO','FINALIZADO'),
    FOREIGN KEY (ID_VET) REFERENCES VET(ID_VET),
    FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER),
    FOREIGN KEY (IDENTIFICATION_PET) REFERENCES PET(ID_PET)
);


INSERT INTO USER (IDENTIFICATION, PHONE, NAME, LASTNAME, EMAIL, PASS, CARGO, STATE)
VALUES ('1234567890', '555-1234', 'Juan', 'Pérez', 'juan@example.com', 'password123', 'ADMIN', 'ACTIVO');

INSERT INTO VET (IDENTIFICATION_ADMIN, ADDRESS, PROFITS, LOSS, STATE)
VALUES (1, 'Calle Principal 123', 1000.00, 200.50, 'ACTIVO');

INSERT INTO MANAGER (ADDRESS_MANAGER, PHONE_MANAGER, FULLNAME, STATE)
VALUES ('Calle Secundaria 456', '555-5678', 'María Gómez', 'ACTIVO');

INSERT INTO RACE (RACE, ID_VET, STATE)
VALUES ('Labrador Retriever', 1, 'ACTIVO');

INSERT INTO PET (ID_VET, IDENTIFICATION_PET, NAME_PET, ID_MANAGER, ID_RACE, COLOR, SIZE, AGE, WEIGHT, STATE)
VALUES (1, 123456, 'Bobby', 1, 1, 'Dorado', 'Mediano', '3 años', '15 kg', 'ACTIVO');

INSERT INTO JOBS (ID_VET, ID_USER, IDENTIFICATION_PET, JOB, COSTS, COST_DESCRIPTION, STATE)
VALUES (1, 1, 1, 'Vacunación', 50.00, 'Vacuna contra la rabia', 'FINALIZADO');
